# 图像的基础知识

1. 图像在编程中就是一个数据结构
    - OpenCV：ndarray表示图像
    - PyTorch：Tensor（本质是向量，体现更很多的物理特性）
    - GUI：Qt  

2. ndarray
    - numpy.ndarray:线性代数

3. 图像的表示：
    - 2/3维矩阵：每个元素 = 图像的一个像素（RGB）（255， 0， 0）
    - 颜色空间：
        - RGB
        - HSV
        - YUV
        - Gray

4. 使用ndarray表示图像
    - 创建图像 = 创建ndarray对象
        - 直接创建
        - 加载创建

In [12]:
import numpy
import cv2
# https://numpy.org/devdocs/reference/index.html
# 直接使用传统的python数组来创建（工厂模式）
# 构建python的数组
img_py = [[[0, 0, 255]  for i in range(50)] for j in range(50)]
img_np = numpy.array(img_py)
img_np
cv2.imwrite("1.png", img_np)   # 图像格式：根据扩展名自动化识别

True

![numpy构建图像](1.png)

- 注意：
    - OpenCV颜色空间默认是BGR

In [14]:
import numpy
import cv2
# 构造器创建
img_constructor = numpy.ndarray(shape=(100, 100), dtype=numpy.uint8)
cv2.imwrite("2.jpg", img_constructor)

True

In [15]:
import numpy
import cv2
# 加载图像为对象
img = cv2.imread("imgs/gpu.bmp")
print(img)

[[[106  31   0]
  [106  30   0]
  [110  31   0]
  ...
  [145  54  19]
  [145  54  19]
  [145  54  19]]

 [[112  36   0]
  [112  34   0]
  [113  34   0]
  ...
  [145  54  19]
  [145  54  19]
  [145  54  19]]

 [[121  43   6]
  [119  41   4]
  [119  39   2]
  ...
  [145  54  19]
  [145  54  19]
  [145  54  19]]

 ...

 [[  0   2   3]
  [  0   2   3]
  [  0   2   3]
  ...
  [ 80  98 175]
  [ 80  98 175]
  [ 80  98 175]]

 [[  0   2   3]
  [  0   2   3]
  [  0   2   3]
  ...
  [ 80  98 174]
  [ 80  98 174]
  [ 80  98 174]]

 [[  0   2   3]
  [  0   2   3]
  [  0   2   3]
  ...
  [ 80  99 174]
  [ 80  99 174]
  [ 80  99 174]]]


4. 图像的基本属性
    - 数组的属性：shape(高度，宽度，通道)
    - 数组的类型
    - 数组的数据（字节数组）

In [26]:
import cv2
img = cv2.imread("imgs/gpu.bmp")
print(img.shape)
print(img.ndim)
print(img.size)
print(img.nbytes)
print(img.itemsize)
print(img.dtype)
print(img.data)
print(type(img.data))
memoryview?
help(memoryview)

(1080, 1920, 3)
3
6220800
6220800
1
uint8
<class 'memoryview'>
Help on class memoryview in module builtins:

class memoryview(object)
 |  Create a new memoryview object which references the given object.
 |  
 |  Methods defined here:
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __enter__(...)
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __exit__(...)
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(self, key, /)
 |      Return self[key].
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash__(self, /)
 |      Return hash(self).
 |  
 |  __le__(self, value, /)
 |      Return self<=value.
 |  
 |  __len__(self, /)
 |      Return len(self).
 |  
 |  __lt__(self, value, /)
 |      Return self<value.
 |  
 |  __ne__(self, value, /)
 |      Return self!=value.
 |  
 |  __new__(*args, **kwargs) from builtins.type
 |

Init signature: memoryview(object)
Docstring:      Create a new memoryview object which references the given object.
Type:           type
Subclasses:     


5. 图像操作
    - 运算符
        - []下标
            1. 标量，元组（推荐：不变）或者列表（可变）
            2. 切片（切片表达式，切片对象）
            3. 逻辑类型的ndarray（与原数组同型）
            4. 支持多参数（与维度一致）
    - 普通函数/方法
        - 见下面6

In [39]:
import cv2
img = cv2.imread("imgs/gpu.bmp")

# img[0]  # 访问行：取值，赋值
# img[0, 1, 1]  # 访问行，img[[0, 1, 1]]  img[(0, 1, 1)]

img[0:2:2]  # 访问行，[start, end)
img[slice(0,2,2)]  # 访问行，[start, end)

# 多参数访问，按照维度坐标访问，多参数必须与数组的维度一致
img[[0, 1], 0, slice(0, 2,1)]

array([[106,  31],
       [112,  36]], dtype=uint8)

In [47]:
import cv2
img_idx = cv2.imread("imgs/gpu.bmp")

# img_idx[::, :, 2:] = 120
# img_idx[::, :, 1:2:] = 0



(img_idx[::, :, 2:])[img_idx[::, :, :] > 200] = 255
cv2.imwrite("4.jpg", img_idx)


True

In [49]:
import numpy as np
arr = np.array([
    [1, 2, 3, 4],
    [3, 4, 5, 6]
])
arr_b = np.array([
    [True,  False, True,  True],
    [False, True,  False, False]
])

arr[arr_b] = 88
arr

array([[88,  2, 88, 88],
       [ 3, 88,  5,  6]])

6. 图像作为矩阵的操作
    1. 矩阵转置 = 图像旋转
        - 维度做逆序交换.T
        - 任意交换transpose
    2. 改变形状
        - reshape （数组元素个数不变）
    3. 改变大小
        - resize：
            - 缩放
            - 截断
    4. 扩维/缩维
        - squeeze(axis=维度)：axis裁剪是的维度的维数必须是1 

In [66]:
import cv2
img = cv2.imread("imgs/gpu.bmp")
# print(img.shape)
# print(img.T.shape)
# img_t = img.transpose(1, 0, 2) 
# print(img_t.shape)
# cv2.imwrite("5.jpg", img_t)
# # 数据维度的改变：Torch： 【N，C， H， W】
# img_s = img.reshape(100, img.shape[0] * img.shape[1] // 100,3)
# cv2.imwrite("6.jpg", img_s)

# img.resize([500,500, 3])    # Cython : refcheck=False
# cv2.imwrite("7.jpg", img)

# print(img.shape)
# print(img[:,:,1:2].shape)
# img_sq = img[:,:,1:2].squeeze(axis=2)
# print(img_sq.shape)
import numpy as np

# img_ex = numpy.expand_dims(img, axis=0)
img_ex = img[:, numpy.newaxis, :, :]
print(img_ex.shape)


(1080, 1, 1920, 3)


7. 其他
    - PIL -> Numpy
        - numpy.array(PIL.Image)
    - Numpy -> Tensor
        - torch.tensor(ndarray/list/tuple)
    - numpy  -> Python
        - ndarray.tolist() 
    - PIL -> Torch
        - toTensor()
    

8. 数组的其他常用操作
    - ndarray.mean(axis=0, dtype=numpy.float)
    - ndarray.sum
    - ndarray.max
    - ndarray.argmax
    - ndarray.astype(numpy.float64)

- 上午的目的：
    - 通过对ndarrya数组的操作，来实现图像的操作。
    - 为后面机器视觉中图像的预处理做准备。

# 图像的特征与卷积

## 卷积

- $$ h(x) = \int  _{-\infty}^{+\infty} f(\tau) g(x - \tau) \mathrm{d}\tau$$

- $ x \to (x , y)$
- $ \tau \to (i, j)$
- 积分$\int$ = 求和$\sum$

$$ h(x, y) = \sum  _{i,j \in [-N, + N]} f(i, j) g(x-i,  y-j) $$

- 局部加权运算
    - g称为原图像
    - f称为conv-kernel卷积核
    - 原图像大小$S \times S$，卷积核$K \times K$，则新的图像大小$(S-K+1) \times (S-K+1)$
        - 为了保持图像大小不变：padding补边。补边：$\dfrac{K-1}{2}$

## OpenCV的卷积运算的例子

1. 卷积核取值采用高斯分布

In [69]:
import cv2

# 读取图像
img = cv2.imread("imgs/gpu.bmp")
# 做高斯卷积运算
img_gauss = cv2.GaussianBlur(img, (15, 15), 10)
# 保存结果图像
cv2.imwrite("8.jpg", img_gauss)

True

2. 手工设置卷积核，取值随意。
    - 原图 -(卷积核)-> Feature-Map

In [73]:
import cv2
import numpy
# 1. 读取图像
img = cv2.imread("imgs/gpu.bmp")
# 2. 定制卷积核
kernel = numpy.array([
    [ -1, -1, -1],
    [  0,  0,  0],
    [  1,  1,  1]
])
# 3. 做卷积运算
# dst=cv.filter2D(src, ddepth, kernel[, dst[, anchor[, delta[, borderType]]]]	)
"""
    src: 原图像
    ddepth：建议指定-1，保持输入与输出的图像深度一致（数据类型，通道：U8C2）
    kernel：定制核
    
"""
img_filter = cv2.filter2D(img, -1, kernel, delta=127)
# 4. 保存图像
cv2.imwrite("9.jpg", img_filter)


True

## 图像特征

- 定义：
    - 特征：变化的像素
        - 图像的微分/导数/梯度

- 图像特征：
    - 1阶微分：Sobel算子   |
    - 2阶微分：Laplace算子 |----卷积运算

In [78]:
"""
dst = cv.Sobel(src, ddepth, dx, dy[, dst[, ksize[, scale[, delta[, borderType]]]]])
    src: 原图
    ddepth：
    dx：x的导数的阶数
    dy：y的导数的阶数
    ksize: 模板的大小
    scale：数乘系数
    delta: 偏移bias
"""
import cv2

# 读取图像
img = cv2.imread("imgs/gpu.bmp")
# sobel特征运算
img_sobel = cv2.Sobel(img, -1, 2, 0, ksize=3, scale=1, delta=127)
# 保存图像
cv2.imwrite("10.jpg", img_sobel)


True

# 应用目标：

- 图形处理的小程序（基础处理 + 特征处理）
    - 小程序应用今天的图像技术。
    - `pip install PyQt5 -i https://pypi.tuna.tsinghua.edu.cn/simple/`
    - `pip install opencv-python -i https://pypi.tuna.tsinghua.edu.cn/simple/`

1. 工程
    - 目录
    - 文件
    - 配置

2. 文件-类结构
    1. AppFrame   继承QDialog
    2. Ui_proc    使用@pyuic5 -o procui.py  proc.ui命令将*.ui->*.py
    

3. UI类
    - `Qt Designer设计UI -> *.py`     @pyuic5 -o procui.py  proc.ui命令

4. 实现逻辑
    1. 走通程序的流程
    2. 交互
    3. 图像的基础处理与特征处理

## 作业

- 完成Qt的图像特征处理的小程序
    - GUI
    - 交互
    - Sobel
    - Laplace
    - 图像基本处理（数组处理像素）

-----